select
		smn_produccion.smn_rel_formula_item_centro_produccion.smn_rel_formula_item_centro_produccion_id,
	smn_produccion.smn_centro_produccion.smn_centro_produccion_id,
	smn_produccion.smn_centro_produccion.cpr_codigo as cpr_codigo_pl0,
	smn_produccion.smn_linea_produccion.smn_linea_produccion_id,
	smn_produccion.smn_linea_produccion.lpr_codigo as lpr_codigo_pl1,
select
		smn_produccion.smn_rel_formula_item_centro_produccion.smn_rel_formula_item_centro_produccion_id,
select
		smn_produccion.smn_rel_formula_item_centro_produccion.smn_rel_formula_item_centro_produccion_id,
select
		smn_produccion.smn_rel_formula_item_centro_produccion.smn_rel_formula_item_centro_produccion_id,
	smn_produccion.smn_rel_formula_item_centro_produccion.smn_rel_formula_item_id,
	smn_produccion.smn_rel_formula_item_centro_produccion.smn_centro_produccion_id,
	smn_produccion.smn_rel_formula_item_centro_produccion.smn_linea_produccion_id,
	smn_produccion.smn_rel_formula_item_centro_produccion.rfc_idioma,
	smn_produccion.smn_rel_formula_item_centro_produccion.rfc_usuario,
	smn_produccion.smn_rel_formula_item_centro_produccion.rfc_fecha_registro,
	smn_produccion.smn_rel_formula_item_centro_produccion.rfc_hora
	
from
	smn_produccion.smn_centro_produccion,
	smn_produccion.smn_linea_produccion,
	smn_produccion.smn_rel_formula_item_centro_produccion
where
	smn_produccion.smn_centro_produccion.smn_centro_produccion_id=smn_produccion.smn_rel_formula_item_centro_produccion.smn_centro_produccion_id and
	smn_produccion.smn_linea_produccion.smn_linea_produccion_id=smn_produccion.smn_rel_formula_item_centro_produccion.smn_linea_produccion_id
