INSERT INTO smn_produccion.smn_orden_produccion_actividad
(
	smn_orden_produccion_actividad_id,
	smn_orden_produccion_id,
	smn_activo_rf,
	smn_centro_produccion_id,
	smn_linea_produccion_id,
	smn_funciones_id,
	opa_hora_inicial,
	opa_hora_final,
	opa_horas,
	smn_unidad_medida_rf,
	opa_estatus,
	opa_fecha_registro
)
VALUES
(
	${seq:nextval@smn_produccion.seq_smn_orden_produccion_actividad},
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	{d '${def:date}'}
)
