select
		smn_produccion.smn_rel_formula_item_equipos.smn_rel_formula_item_equipos_id,
select
		smn_produccion.smn_rel_formula_item_equipos.smn_rel_formula_item_equipos_id,
select
		smn_produccion.smn_rel_formula_item_equipos.smn_rel_formula_item_equipos_id,
	smn_produccion.smn_rel_formula_item_equipos.smn_rel_formula_item_id,
	smn_produccion.smn_rel_formula_item_equipos.smn_activo_id,
	smn_produccion.smn_rel_formula_item_equipos.rfe_cantidad,
	smn_produccion.smn_rel_formula_item_equipos.smn_unidad_medida_rf,
	smn_produccion.smn_rel_formula_item_equipos.rfe_fecha_registro
	
from
	smn_produccion.smn_rel_formula_item_equipos
